# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build & Check for Changeset"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install

      - run: npm run build

      - name: "Git inspection (TEST): git pull -f origin main:main"
        run: git pull -f origin main:main

      - name: "Git inspection (TEST): git merge-base main HEAD"
        run: git merge-base main HEAD

      - name: "Git inspection (TEST): git merge-base origin/main HEAD"
        run: git merge-base origin/main HEAD

      - name: "Git inspection (TEST): git branch -r"
        run: git branch -r

      - name: Check for Changeset
        run: yarn changeset status --since=main
